#!/usr/bin/env python

def main():
    from optparse import OptionParser
    usage = "usage: %prog publish [--output=output_dir] template_dir"
    #usage += "\n      %prog generate output_dir structure_file"
    parser = OptionParser(usage=usage)
    parser.add_option('-o', '--output', dest='output_dir')
    
    (options, args) = parser.parse_args()
    
    if len(args) < 1:
        parser.error('must provide a template directory')
    
    from publisher import Publisher
    
    if options.output_dir:
        runner = Publisher(args[1], options.output_dir)
        runner()
    else:
        runner = Publisher(args[1])
        runner()
    

if __name__ == "__main__":
    main()

